apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pod
      namespace: chat-app
      labels: 
        app: backend
    spec:
     containers:
      - name: chatapp-backend
        image: shahwaz131/chatapp-backend:latest
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: production
        - name: MONGODB_URI
          value: "mongodb://admin:root@mongodb:27017/chatApp?authSource=admin&retryWrites=true&w=majority"
        - name: PORT
          value: "5001"
        - name: JWT_SECRET
          value: "sdjkfjsgfjuiseurfbsebuseuifiuseuifbuifgbuisbiugbasifvbsiabfiuaiuef"  